apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: countervalve-tls
spec:
  # location to store the incoming certificate after it's obtained by Cert Manager
  secretName: countervalve-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: countervalve.com
  dnsNames:
    - countervalve.com
    - www.countervalve.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - countervalve.com
          - www.countervalve.com
