apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    # create an ingress controller based on the nginx project
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    # configure how the actual copy of nginx behaves
    # eg below command removes the '/api' from the request url string
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
