apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
spec:
  replicas: 3
  selector:
  # selector - deployment is going to use this attribute to find the set of pods that its supposed to control
    matchLabels:
      component: server
  template:
  # configuration for pods
    metadata:
      labels:
        component: server
    spec:
      # exact behaviour of each pod that gets created
      containers:
        - name: server
          image: nanda1995/multi-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value:  redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              # name of the cluster ip service managing access to the postgres pod
              value:  postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
